In [3]:
import pandas as pd

In [6]:
df1 = pd.read_csv('Unemployment.csv')

In [7]:
df1

,State,Area_name,Civilian_labor_force_2007,Employed_2007,Unemployed_2007,Unemployment_rate_2007,Civilian_labor_force_2008,Employed_2008,Unemployed_2008,Unemployment_rate_2008,...,Civilian_labor_force_2016,Employed_2016,Unemployed_2016,Unemployment_rate_2016,Civilian_labor_force_2017,Employed_2017,Unemployed_2017,Unemployment_rate_2017,Median_Household_Income_2016,Med_HH_Income_Percent_of_State_Total_2016
0,AL,Alabama,"2,175,612","2,089,127","86,485",4.0,"2,176,489","2,053,477","123,012",5.7,...,"2,173,175","2,045,624","127,551",5.9,2168444,2073106,95338,4.4,"$46,309",100.0
1,AK,Alaska,"350,785","328,579","22,206",6.3,"356,109","332,285","23,824",6.7,...,"363,047","337,947","25,100",6.9,362783,336806,25977,7.2,"$76,144",100.0
2,AZ,Arizona,"3,034,016","2,917,117","116,899",3.9,"3,104,863","2,913,903","190,960",6.2,...,"3,225,703","3,052,788","172,915",5.4,3312720,3151405,161315,4.9,"$53,481",100.0
3,AR,Arkansas,"1,369,284","1,296,572","72,712",5.3,"1,375,257","1,300,017","75,240",5.5,...,"1,342,561","1,289,549","53,012",3.9,1354265,1304434,49831,3.7,"$44,406",100.0
4,CA,California,"17,893,080","16,931,590","961,490",5.4,"18,178,123","16,854,482","1,323,641",7.3,...,"19,093,658","18,048,827","1,044,831",5.5,19311958,18393077,918881,4.8,"$67,715",100.0
5,Co,Colorado,"2,664,677","2,565,218","99,459",3.7,"2,716,625","2,585,243","131,382",4.8,...,"2,893,268","2,798,928","94,340",3.3,2992307,2907468,84839,2.8,"$65,718",100.0
6,CT,Connecticut,"1,856,209","1,773,159","83,050",4.5,"1,881,454","1,774,681","106,773",5.7,...,"1,904,556","1,806,575","97,981",5.1,1918576,1828858,89718,4.7,"$73,380",100.0
7,DE,Delaware,"443,573","428,312","15,261",3.4,"447,041","424,914","22,127",4.9,...,"473,881","452,434","21,447",4.5,477349,455427,21922,4.6,"$62,112",100.0
8,DC,District of Columbia,"322,237","304,426","17,811",5.5,"330,544","309,192","21,352",6.5,...,"394,586","370,521","24,065",6.1,400894,376633,24261,6.1,"$74,093",100.0
9,FL,Florida,"9,157,124","8,789,770","367,354",4.0,"9,215,524","8,637,164","578,360",6.3,...,"9,846,000","9,373,059","472,941",4.8,10100266,9680820,419446,4.2,"$50,857",100.0
10,GA,Georgia,"4,815,818","4,597,640","218,178",4.5,"4,879,253","4,575,010","304,243",6.2,...,"4,926,945","4,662,849","264,096",5.4,5061399,4821622,239777,4.7,"$53,468",100.0
11,HI,Hawaii,"638,395","620,535","17,860",2.8,"639,691","612,120","27,571",4.3,...,"684,167","664,032","20,135",2.9,685418,669241,16177,2.4,"$74,659",100.0
12,ID,Idaho,"754,438","731,235","23,203",3.1,"755,153","716,653","38,500",5.1,...,"812,856","782,279","30,577",3.8,833462,807163,26299,3.2,"$51,647",100.0
13,IL,Illinois,"6,665,601","6,334,010","331,591",5.0,"6,657,227","6,238,611","418,616",6.3,...,"6,549,991","6,169,560","380,431",5.8,6492578,6170676,321902,5.0,"$60,977",100.0
14,IN,Indiana,"3,207,687","3,061,042","146,645",4.6,"3,232,097","3,041,828","190,269",5.9,...,"3,327,139","3,180,104","147,035",4.4,3320409,3203351,117058,3.5,"$52,289",100.0
15,IA,Iowa,"1,660,677","1,599,332","61,345",3.7,"1,679,293","1,608,695","70,598",4.2,...,"1,696,113","1,634,964","61,149",3.6,1678549,1626036,52513,3.1,"$56,354",100.0
16,KS,Kansas,"1,483,458","1,420,449","63,009",4.2,"1,499,676","1,430,628","69,048",4.6,...,"1,485,336","1,425,413","59,923",4.0,1478783,1425216,53567,3.6,"$54,828",100.0
17,KY,Kentucky,"2,032,082","1,922,220","109,862",5.4,"2,030,738","1,900,683","130,055",6.4,...,"2,012,279","1,909,158","103,121",5.1,2052368,1952066,100302,4.9,"$46,610",100.0
18,LA,Louisiana,"2,030,434","1,944,038","86,396",4.3,"2,084,835","1,982,381","102,454",4.9,...,"2,125,934","1,997,358","128,576",6.0,2112320,2004003,108317,5.1,"$45,374",100.0
19,ME,Maine,"700,468","667,781","32,687",4.7,"701,646","663,158","38,488",5.5,...,"692,154","665,911","26,243",3.8,700099,677141,22958,3.3,"$52,926",100.0
20,MD,Maryland,"2,970,094","2,867,348","102,746",3.5,"3,001,953","2,874,987","126,966",4.2,...,"3,178,646","3,037,763","140,883",4.4,3219455,3086246,133209,4.1,"$78,787",100.0
21,MA,Massachusetts,"3,426,009","3,268,096","157,913",4.6,"3,452,468","3,261,408","191,060",5.5,...,"3,611,418","3,471,112","140,306",3.9,3657173,3521482,135691,3.7,"$75,207",100.0
22,MI,Michigan,"5,011,120","4,658,939","352,181",7.0,"4,921,466","4,529,289","392,177",8.0,...,"4,840,281","4,599,266","241,015",5.0,4883815,4657272,226543,4.6,"$52,436",100.0
23,MN,Minnesota,"2,906,390","2,773,704","132,686",4.6,"2,925,088","2,766,342","158,746",5.4,...,"3,036,278","2,919,097","117,181",3.9,3063604,2957838,105766,3.5,"$65,583",100.0
24,MS,Mississippi,"1,303,514","1,224,059","79,455",6.1,"1,306,772","1,220,991","85,781",6.6,...,"1,278,960","1,204,481","74,479",5.8,1280071,1215115,64956,5.1,"$41,793",100.0
25,MO,Missouri,"3,034,579","2,879,647","154,932",5.1,"3,028,857","2,842,845","186,012",6.1,...,"3,079,559","2,939,309","140,250",4.6,3050713,2936126,114587,3.8,"$51,713",100.0
26,MT,Montana,"502,070","484,189","17,881",3.6,"509,163","483,347","25,816",5.1,...,"521,628","499,990","21,638",4.1,525453,504279,21174,4.0,"$50,265",100.0
27,NE,Nebraska,"978,763","949,494","29,269",3.0,"989,757","956,759","32,998",3.3,...,"1,008,715","977,622","31,093",3.1,1007011,977444,29567,2.9,"$56,979",100.0
28,NV,Nevada,"1,330,396","1,270,572","59,824",4.5,"1,363,574","1,272,187","91,387",6.7,...,"1,430,344","1,348,265","82,079",5.7,1462955,1389372,73583,5.0,"$55,201",100.0
29,NH,New Hampshire,"737,942","712,008","25,934",3.5,"742,781","714,104","28,677",3.9,...,"746,452","725,154","21,298",2.9,746549,726607,19942,2.7,"$70,986",100.0
30,NJ,New Jersey,"4,441,797","4,251,815","189,982",4.3,"4,504,432","4,263,965","240,467",5.3,...,"4,530,784","4,305,516","225,268",5.0,4518832,4309706,209126,4.6,"$76,212",100.0
31,NM,New Mexico,"934,027","898,998","35,029",3.8,"944,548","902,411","42,137",4.5,...,"928,732","866,704","62,028",6.7,929567,872382,57185,6.2,"$46,844",100.0
32,NY,New York,"9,522,056","9,088,207","433,849",4.6,"9,664,773","9,139,080","525,693",5.4,...,"9,668,687","9,200,266","468,421",4.8,9704695,9249225,455470,4.7,"$62,700",100.0
33,NC,North Carolina,"4,512,856","4,300,304","212,552",4.7,"4,560,059","4,281,713","278,346",6.1,...,"4,854,828","4,608,229","246,599",5.1,4941701,4716832,224869,4.6,"$50,595",100.0
34,ND,North Dakota,"367,234","355,766","11,468",3.1,"371,025","359,333","11,692",3.2,...,"414,431","401,671","12,760",3.1,414399,403610,10789,2.6,"$61,898",100.0
35,OH,Ohio,"5,990,292","5,657,718","332,574",5.6,"5,965,166","5,580,843","384,323",6.4,...,"5,739,296","5,451,315","287,981",5.0,5780021,5491174,288847,5.0,"$52,357",100.0
36,OK,Oklahoma,"1,726,259","1,655,490","70,769",4.1,"1,746,466","1,681,081","65,385",3.7,...,"1,829,413","1,741,277","88,136",4.8,1834312,1755604,78708,4.3,"$49,204",100.0
37,OR,Oregon,"1,921,766","1,822,772","98,994",5.2,"1,955,121","1,827,352","127,769",6.5,...,"2,049,480","1,951,218","98,262",4.8,2104078,2017292,86786,4.1,"$57,379",100.0
38,PA,Pennsylvania,"6,342,997","6,064,063","278,934",4.4,"6,451,535","6,109,645","341,890",5.3,...,"6,452,812","6,105,223","347,589",5.4,6427370,6111633,315737,4.9,"$56,897",100.0
39,RI,Rhode Island,"573,173","543,401","29,772",5.2,"570,328","525,941","44,387",7.8,...,"553,555","524,745","28,810",5.2,554658,529867,24791,4.5,"$60,046",100.0
40,SC,South Carolina,"2,125,891","2,005,686","120,205",5.7,"2,142,232","1,996,409","145,823",6.8,...,"2,293,666","2,179,521","114,145",5.0,2312651,2213894,98757,4.3,"$49,587",100.0
41,SD,South Dakota,"442,499","430,011","12,488",2.8,"446,618","432,925","13,693",3.1,...,"451,934","438,377","13,557",3.0,455175,440028,15147,3.3,"$54,926",100.0
42,TN,Tennessee,"3,063,669","2,920,352","143,317",4.7,"3,054,785","2,853,746","201,039",6.6,...,"3,134,725","2,987,074","147,651",4.7,3198767,3080210,118557,3.7,"$48,506",100.0
43,TX,Texas,"11,431,631","10,941,413","490,218",4.3,"11,664,390","11,104,115","560,275",4.8,...,"13,317,176","12,702,122","615,054",4.6,13538385,12960595,577790,4.3,"$56,583",100.0
44,UT,Utah,"1,359,129","1,324,060","35,069",2.6,"1,371,201","1,322,089","49,112",3.6,...,"1,511,279","1,459,309","51,970",3.4,1560846,1510208,50638,3.2,"$65,931",100.0
45,VT,Vermont,"353,739","339,547","14,192",4.0,"354,899","338,273","16,626",4.7,...,"344,572","333,399","11,173",3.2,344760,334378,10382,3.0,"$57,661",100.0
46,VA,Virginia,"4,036,835","3,914,087","122,748",3.0,"4,133,443","3,970,428","163,015",3.9,...,"4,242,650","4,069,139","173,511",4.1,4307753,4146134,161619,3.8,"$68,127",100.0
47,WA,Washington,"3,403,163","3,243,308","159,855",4.7,"3,478,577","3,291,309","187,268",5.4,...,"3,635,200","3,444,126","191,074",5.3,3724722,3547430,177292,4.8,"$67,064",100.0
48,WV,West Virginia,"811,160","773,990","37,170",4.6,"812,905","777,560","35,345",4.3,...,"781,600","733,980","47,620",6.1,778821,738309,40512,5.2,"$43,175",100.0
49,WI,Wisconsin,"3,087,828","2,936,452","151,376",4.9,"3,091,796","2,940,438","151,358",4.9,...,"3,130,520","3,005,478","125,042",4.0,3151909,3048242,103667,3.3,"$56,808",100.0
50,WY,Wyoming,"286,560","278,486","8,074",2.8,"293,279","284,310","8,969",3.1,...,"300,922","285,052","15,870",5.3,293347,281017,12330,4.2,"$61,686",100.0
51,PR,Puerto Rico,"1,387,359","1,232,266","155,093",11.2,"1,345,923","1,187,398","158,525",11.8,...,"1,117,909","986,142","131,767",11.8,1102646,983264,119382,10.8,NaN,NaN
52,US,United States,"152,191,093","145,156,134","7,034,959",4.6,153761095,144860350,8900745,5.8,...,"158,921,892","151,183,680","7,738,212",4.9,"160,588,515","153,594,100","6,994,415",4.4,"$57,617",NaN

In [8]:
df2 = pd.read_csv('Education.csv')

In [9]:
df2

,State,Area name,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970","Four years of college or higher, 1970","Percent of adults with less than a high school diploma, 1970","Percent of adults with a high school diploma only, 1970","Percent of adults completing some college (1-3 years), 1970","Percent of adults completing four years of college or higher, 1970",...,"Percent of adults with a bachelor's degree or higher, 2000","Less than a high school diploma, 2012-2016","High school diploma only, 2012-2016","Some college or associate's degree, 2012-2016","Bachelor's degree or higher, 2012-2016","Percent of adults with less than a high school diploma, 2012-2016","Percent of adults with a high school diploma only, 2012-2016","Percent of adults completing some college or associate's degree, 2012-2016","Percent of adults with a bachelor's degree or higher, 2012-2016",Unnamed: 42
0,AL,Alabama,"1,062,306","468,269","136,287","141,936",58.7,25.9,7.5,7.8,...,19.0,"496,036","1,009,593","972,703","783,076",15.2,31.0,29.8,24.0,NaN
1,AK,Alaska,"44,994","50,820","20,052","19,082",33.3,37.7,14.9,14.1,...,24.7,"36,032","130,511","168,631","135,525",7.7,27.7,35.8,28.8,NaN
2,AZ,Arizona,"383,873","289,781","127,063","115,020",41.9,31.6,13.9,12.6,...,23.5,"611,243","1,078,358","1,509,609","1,241,425",13.8,24.3,34.0,28.0,NaN
3,AR,Arkansas,"635,149","271,150","80,835","70,378",60.1,25.6,7.6,6.7,...,16.7,"292,228","683,886","573,031","424,446",14.8,34.7,29.0,21.5,NaN
4,CA,California,"4,062,367","3,566,578","1,784,772","1,462,266",37.4,32.8,16.4,13.4,...,26.6,"4,572,963","5,260,904","7,544,058","8,176,487",17.9,20.6,29.5,32.0,NaN
5,CO,Colorado,"411,837","392,787","166,188","170,326",36.1,34.4,14.6,14.9,...,32.7,"323,691","780,033","1,096,896","1,389,730",9.0,21.7,30.6,38.7,NaN
6,CT,Connecticut,"740,830","534,830","179,635","230,303",44.0,31.7,10.7,13.7,...,31.4,"242,932","673,220","611,658","938,319",9.9,27.3,24.8,38.0,NaN
7,DE,Delaware,"130,463","91,211","28,091","37,630",45.4,31.7,9.8,13.1,...,25.0,"71,746","199,461","174,387","195,321",11.2,31.1,27.2,30.5,NaN
8,DC,District of Columbia,"189,720","110,767","47,331","75,233",44.8,26.2,11.2,17.8,...,39.1,"46,510","83,367","76,804","256,316",10.0,18.0,16.6,55.4,NaN
9,FL,Florida,"1,882,537","1,219,216","458,864","407,264",47.4,30.7,11.6,10.3,...,22.3,"1,807,386","4,111,029","4,245,476","3,929,796",12.8,29.2,30.1,27.9,NaN
10,GA,Georgia,"1,399,175","528,537","211,101","216,997",59.4,22.4,9.0,9.2,...,24.3,"932,810","1,850,601","1,867,961","1,938,090",14.2,28.1,28.3,29.4,NaN
11,HI,Hawaii,"146,701","138,307","46,088","53,747",38.1,35.9,12.0,14.0,...,26.2,"84,943","270,583","312,218","305,201",8.7,27.8,32.1,31.4,NaN
12,ID,Idaho,"149,531","127,462","55,171","36,748",40.5,34.6,15.0,10.0,...,21.7,"105,170","289,085","378,367","274,984",10.0,27.6,36.1,26.2,NaN
13,IL,Illinois,"2,885,938","1,944,720","630,845","627,825",47.4,31.9,10.4,10.3,...,26.1,"1,008,608","2,287,126","2,487,681","2,834,869",11.7,26.5,28.9,32.9,NaN
14,IN,Indiana,"1,292,237","991,710","233,791","228,676",47.1,36.1,8.5,8.3,...,19.4,"517,458","1,486,051","1,268,116","1,068,062",11.9,34.2,29.2,24.6,NaN
15,IA,Iowa,"632,366","596,649","171,454","140,119",41.0,38.7,11.1,9.1,...,21.2,"169,966","656,680","672,763","559,431",8.3,31.9,32.7,27.2,NaN
16,KS,Kansas,"492,098","438,583","155,828","139,479",40.1,35.8,12.7,11.4,...,25.8,"182,049","499,895","602,750","593,801",9.7,26.6,32.1,31.6,NaN
17,KY,Kentucky,"1,053,196","412,640","123,919","123,543",61.5,24.1,7.2,7.2,...,17.1,"456,180","990,322","849,406","674,165",15.4,33.3,28.6,22.7,NaN
18,LA,Lousiana,"1,046,551","446,400","153,171","163,792",57.8,24.7,8.5,9.0,...,18.7,"496,210","1,038,591","827,303","703,875",16.2,33.9,27.0,23.0,NaN
19,ME,Maine,"243,532","188,886","60,424","44,981",45.3,35.1,11.2,8.4,...,22.9,"77,305","317,373","281,818","280,570",8.1,33.2,29.4,29.3,NaN
20,MD,Maryland,"992,786","593,295","206,230","290,238",47.7,28.5,9.9,13.9,...,31.4,"420,756","1,030,305","1,044,867","1,556,711",10.4,25.4,25.8,38.4,NaN
21,MA,Massachusetts,"1,305,345","1,096,249","346,399","394,470",41.5,34.9,11.0,12.6,...,33.2,"462,385","1,167,098","1,103,708","1,916,806",9.9,25.1,23.7,41.2,NaN
22,MI,Michigan,"2,170,415","1,546,679","444,452","432,915",47.2,33.7,9.7,9.4,...,21.8,"676,467","1,978,662","2,195,954","1,831,798",10.1,29.6,32.9,27.4,NaN
23,MN,Minnesota,"844,065","687,242","238,128","220,932",42.4,34.5,12.0,11.1,...,27.4,"270,121","940,315","1,197,761","1,253,937",7.4,25.7,32.7,34.2,NaN
24,MS,Mississippi,"656,198","266,121","99,907","89,563",59.0,23.9,9.0,8.1,...,16.9,"332,266","593,422","614,104","409,891",17.0,30.4,31.5,21.0,NaN
25,MO,Missouri,"1,332,385","795,144","241,285","233,465",51.2,30.6,9.3,9.0,...,21.6,"454,882","1,267,813","1,225,017","1,125,665",11.2,31.1,30.1,27.6,NaN
26,MT,Montana,"148,759","124,113","51,500","40,136",40.8,34.0,14.1,11.0,...,24.4,"49,627","207,929","231,806","209,072",7.1,29.8,33.2,29.9,NaN
27,NE,Nebraska,"327,773","299,440","99,767","77,643",40.7,37.2,12.4,9.6,...,23.7,"113,944","330,629","411,872","366,783",9.3,27.0,33.7,30.0,NaN
28,NV,Nevada,"92,220","103,235","41,042","28,592",34.8,38.9,15.5,10.8,...,18.2,"280,240","544,288","652,036","445,561",14.6,28.3,33.9,23.2,NaN
29,NH,New Hampshire,"168,709","136,982","48,837","43,153",42.4,34.4,12.3,10.9,...,28.7,"69,274","264,372","268,022","330,676",7.4,28.4,28.7,35.5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
402,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
403,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
406,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
408,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
410,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
411,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
412,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
413,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
414,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
417,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
420,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
422,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
423,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
424,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
427,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
431,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN